### ISSUE TITLE
HTTPError

### ISSUE THREAD

**Issue by thekevinava** [iamtraction/google-translate-api#20]
It was working so well, but now shows an error when translating:
`Error [HTTPError]
    at translate (C:\...\node_modules\@k3rn31p4nic\google-translate-api\src\index.js:143:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  name: 'HTTPError',
  statusCode: undefined,
  statusMessage: undefined
}`

**Comment by k3rn31p4nic** [comment]
Can you give a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by sapphir1** [comment]
const translate = require('@k3rn31p4nic/google-translate-api');

translate('Thank you', { from: 'en', to: 'fr' }).then(res => {
  console.log(res.text); // OUTPUT: Je vous remercie
  console.log(res.from.autoCorrected); // OUTPUT: true
  console.log(res.from.text.value); // OUTPUT: [Thank] you
  console.log(res.from.text.didYouMean); // OUTPUT: false
}).catch(err => {
  console.error(err);
});

I got an HTTPError as well for this sample.

**Comment by iamtraction** [comment]
Which HTTP Error exactly? Can you show the error?
